// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc-9onUG4d9i-DPZswxMl3oebXbDIaNPI',
    appId: '1:645760022007:web:4afe41e5a399c866de6af2',
    messagingSenderId: '645760022007',
    projectId: 'med-dash-enterprise',
    authDomain: 'med-dash-enterprise.firebaseapp.com',
    storageBucket: 'med-dash-enterprise.firebasestorage.app',
    measurementId: 'G-W0B6WCWYQD',
  );
  static const FirebaseOptions android = FirebaseOptions(
  apiKey: 'AIzaSyApiETEYP92UeQ4xZsntVbqKeC3saexVU4',        // Found in current_key
  appId: '1:645760022007:android:55f1bc741002ffc7de6af2',    // Found in mobilesdk_app_id
  messagingSenderId: '645760022007', // Matches your web sender ID
  projectId: 'med-dash-enterprise',
  storageBucket: 'med-dash-enterprise.firebasestorage.app',
  );
}
